### Info
GET http://localhost:3000/api/player_api.php

### Series Categories
GET http://localhost:3000/api/player_api.php?action=get_series_categories

### Series
GET http://localhost:3000/api/player_api.php?action=get_series

### Stream
GET http://localhost:3000/api/movie/30100479.mp4

